# Generated by Django 2.2 on 2019-05-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190515_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='articles',
        ),
    ]
