# Generated by Django 2.2 on 2019-05-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190515_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
