# Generated by Django 2.2 on 2019-05-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190515_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Article'),
        ),
    ]
